### PR TITLE
Added YC F1 companies based on public information

### PR DESCRIPTION
**Pull request by jancurn**
Added YC F1 companies that publicly revealed they participated in the YCF. Disclaimer: we're one of them.

### CODE REVIEW

**Comment by linrock** [comment]
awesome, thanks!

**Comment by jancurn** [comment]
No problem! I just noticed two things:
1) The favicons for F1 are incorrect, as well as for many other companies (see redit, dropbox etc.). Can that be because I incorrectly uploaded PNG files in higher resolution than 16x16?
2) F1 was after S15

**Comment by linrock** [comment]
@jancurn oops, thanks for catching that! a bug in the static file exporter caused the favicons to be wrong. i also just moved F1 to after S15

**Comment by jancurn** [comment]
awesome, great job

**Pull request merged**
